export const BLOCKS = [
  {
    id: "4",
    name: "Header",
    balise: "header",
    style: {
      width: "100%",
      minHeight: "30vh",
      backgroundColor: "grey",
      padding: "2em",
    },
    content: "",
    contentEditable: false,
    isAbleToHaveChildren: true,
    children: [],
  },

  {
    id: "6",
    name: " titre",
    balise: "h1",
    content: "Saisir un titre",
    style: {
      textAlign: "center",
    },
    contentEditable: true,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "10",
    name: "Paragraphe",
    balise: "p",
    content:
      "Ut consectetur dapibus libero sed cursus. Fusce auctor condimentum est, eget laoreet nulla suscipit eget. Donec aliquet tellus id mauris aliquet, nec commodo mi blandit. Fusce finibus rutrum augue, sed euismod nulla vestibulum vel. Maecenas tellus eros, convallis ac enim at, feugiat fringilla nisi. Nam eget libero quam.",
    style: {
      maxWidth: "400px",
      margin: "auto",
    },
    contentEditable: true,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "33",
    name: "inline",
    balise: "div",
    style: {
      backgroundColor: "",
      width: "100%",
      minHeight: "100px",
      display: "flex",
      flexWrap: "wrap",
      alignContent: "center",
      justifyContent: "center",
      gap: "2em",
    },
    content: "",
    contentEditable: false,
    isAbleToHaveChildren: true,
    children: [],
  },
  {
    id: "7",
    name: "grille",
    balise: "div",
    content: "",
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr",
      width: "100%",
      padding: "2em",
      minHeight: "30vh",
      justifyItems: "center",
      alignItems: "center",
      gap: "2em",
    },
    contentEditable: false,
    isAbleToHaveChildren: true,
    children: [],
  },
  {
    id: "12",
    name: "Espace",
    balise: "div",
    content: "",
    style: {
      height: "30px",
      width: "100px",
    },
    contentEditable: false,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "1",
    name: "cube rouge",
    balise: "div",
    style: {
      backgroundColor: "red",
      width: "200px",
      height: "200px",
    },
    content: "",
    contentEditable: false,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "23",
    name: "cube bleu",
    balise: "div",
    style: {
      backgroundColor: "#4d85f5",
      width: "200px",
      height: "200px",
    },
    content: "",
    contentEditable: false,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "22",
    name: "cube vert",
    balise: "div",
    style: {
      backgroundColor: "rgb(48, 245, 48)",
      width: "200px",
      height: "200px",
    },
    content: "",
    contentEditable: false,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "21",
    name: "cube noir",
    balise: "div",
    style: {
      backgroundColor: "black",
      width: "200px",
      height: "200px",
    },
    content: "",
    contentEditable: false,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "20",
    name: "cube jaune",
    balise: "div",
    style: {
      backgroundColor: "#fdeb1f",
      width: "200px",
      height: "200px",
    },
    content: "",
    contentEditable: false,
    isAbleToHaveChildren: false,
    children: [],
  },
];
