export const BLOCKS = [
  {
    id: "4",
    name: "Header",
    content: `<header style="background:grey; width:100%;min-height:30vh; margin:auto; padding: 2em;">  </header>`,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "1",
    name: "cube rouge",
    content: `<div style="background:red; width:fit-content;padding: 2em;"> </div>`,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "2",
    name: "cube bleu",
    content: `<div style="background:blue; width:fit-content; margin:auto; padding: 2em;"> </div>`,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "3",
    name: "cube vert",
    content: `<div style="background:green; width:fit-content; margin:auto; padding: 2em;"> </div>`,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "5",
    name: "cube orange",
    content: `<div style="background:orange; width:fit-content; margin:auto; padding: 2em;"> </div>`,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "6",
    name: " titre",
    content: `<h1 style="text-align:center"> </h1>`,
    isAbleToHaveChildren: false,
    children: [],
  },
  {
    id: "7",
    name: "grille",
    isAbleToHaveChildren: true,
    children: [],
    contentStart: "<div>",
    contentEnd: "</div>",
    style: {
      background: "lightGrey",
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      width: "100%",
      padding: "2em",
      minHeight: "30vh",
    },
  },
];
